const express = require("express");
const router = express.Router();
const AuthRoutes = require("./authRoutes");
const cargoRoutes = require("./cargoRoutes");
const cargoTypeRoutes = require("./cargoTypeRoutes");
const transportRoutes = require("./transportRoutes");
const transportTypeRoutes = require("./transportTypeRoutes");
const userRoutes = require("./userRoutes");
const chatRoutes = require("./chatRoutes");
const countryRoutes = require("./countryRoutes");
const transportationTypesRoutes = require("./transportationTypeRoutes");
const dangerousTypes = require("./dangerousTypeRoutes");
const truckBodyTypes = require("./truckBodyRoutes");
const checkAdminAuth = require("../../middlewares/adminAuth");
router.use("/", AuthRoutes);
router.use("/cargo", checkAdminAuth, cargoRoutes);
router.use("/cargo-type", checkAdminAuth, cargoTypeRoutes);
router.use("/transport", checkAdminAuth, transportRoutes);
router.use("/transport-type", checkAdminAuth, transportTypeRoutes);
router.use("/users", checkAdminAuth, userRoutes);
router.use("/chat", checkAdminAuth, chatRoutes);
router.use("/country", checkAdminAuth, countryRoutes);
router.use("/transportation-type", checkAdminAuth, transportationTypesRoutes);
router.use("/dangerous-type", checkAdminAuth, dangerousTypes);
router.use("/truck-body", checkAdminAuth, truckBodyTypes);
module.exports = router;